### ISSUE TITLE
可能是显卡驱动的问题，你可以更新一下驱动试试。我两台电脑，一台电脑也是这样，更新驱动后就可以了。> > @jj391 安装的时候有个调式的库的可选项，记得勾选一下对应平台，我安装完就没问题了

### ISSUE THREAD

**Issue by jj391** [BoomingTech/Piccolo#170]
> > @jj391 安装的时候有个调式的库的可选项，记得勾选一下对应平台，我安装完就没问题了
> 
> 可以了。谢谢啊

为什么我安装了，勾选调试的可选项，还是不行，请问有什么其他需要配置的吗
![企业微信截图_20220415101846](https://user-images.githubusercontent.com/10347684/163507454-635ad844-c7db-4d56-942f-b00324fdf6f9.png)

_Originally posted by @WenjianShao in https://github.com/BoomingTech/Pilot/issues/23#issuecomment-1099789833_

**Comment by hyv1001** [comment]
是你的Release版本没问题，但Debug版本崩溃的问题吗
