### ISSUE TITLE
Bug Report 编译完的引擎无法最大化

### ISSUE THREAD

**Issue by deltaLRD** [BoomingTech/Piccolo#173]
Windows下运行引擎，然后点最大化，然后就卡死，如果同时还在看视频的化视频也会变卡，鼠标移动也会变慢

**Desktop | 桌面环境**
 - OS: [e.g. Windows, macOS, Linux]
 - Version [e.g. Win10, Bug Sur, Ubuntu20]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]
 - Compiler [e.g. MSVC2019]

**Comment by hyv1001** [comment]
有可能是显存不足导致的，你的GPU型号是什么

**Comment by deltaLRD** [comment]
> 

emmmm, xe 核显 [捂脸]

**Comment by Morcki** [comment]
我和你的问题很相似，可以参考一下#244 的解决方案。
