### ISSUE TITLE
MACOS M1 运行 PilotEditor闪退

### ISSUE THREAD

**Issue by wingsZz** [BoomingTech/Piccolo#186]
**Describe the bug | Bug描述**
MACOS M1 编译成功，运行PilotEditor闪退

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Terminal [80373]
Path:                  /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
Identifier:            com.apple.Terminal
Version:               2.12.5 (444)
Build Info:            Terminal-444000000000000~12
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-05-17 13:38:45.4810 +0800
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Anonymous UUID:        94BEED79-EFA8-7E1B-6C84-4BFAF24BFD18

Time Awake Since Boot: 590000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00005ffffffffff5
Exception Codes:       0x0000000000000001, 0x00005ffffffffff5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [80373]

VM Region Info: 0x5ffffffffff5 is not in any region.  Bytes after previous region: 105072079929334  Bytes before following region: 11
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	       0x188045310 _platform_memmove + 544
1   Terminal                      	       0x104bac744 0x104b84000 + 165700
2   Terminal                      	       0x104bac638 0x104b84000 + 165432
3   Terminal                      	       0x104bb799c 0x104b84000 + 211356
4   Terminal                      	       0x104bb7828 0x104b84000 + 210984
5   Terminal                      	       0x104bd6a84 0x104b84000 + 338564
6   Terminal                      	       0x104bd4f9c 0x104b84000 + 331676
7   AppKit                        	       0x18ac60210 -[NSApplication(NSPersistentUIRestorationSupport) restoreWindowWithIdentifier:state:completionHandler:] + 268
8   AppKit                        	       0x18ac5fd84 -[NSApplication(NSPersistentUIRestorationSupport) _restoreWindowWithRestoration:completionHandler:] + 572
9   AppKit                        	       0x18b7835f8 -[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:requireSecureCoding:completionHandler:] + 1456
10  AppKit                        	       0x18ac5efb8 -[NSPersistentUIManager restoreAllPersistentStateWithCompletionHandler:] + 332
11  AppKit                        	       0x18ac5e2c8 -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:completionHandler:] + 420
12  AppKit                        	       0x18af412e0 -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] + 248
13  AppKit                        	       0x18ac5dc10 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 868
14  Foundation                    	       0x188fa79e8 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 348
15  Foundation                    	       0x188fa7820 _NSAppleEventManagerGenericHandler + 96
16  AE                            	       0x18e8858f4 0x18e87a000 + 47348
17  AE                            	       0x18e88524c 0x18e87a000 + 45644
18  AE                            	       0x18e87e3f8 aeProcessAppleEvent + 488
19  HIToolbox                     	       0x190d2a3fc AEProcessAppleEvent + 68
20  AppKit                        	       0x18ac57f04 _DPSNextEvent + 1844
21  AppKit                        	       0x18ac56424 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
22  AppKit                        	       0x18ac485f0 -[NSApplication run] + 596
23  AppKit                        	       0x18ac19d08 NSApplicationMain + 1132
24  dyld                          	       0x105071088 start + 516

Thread 1:
0   libsystem_pthread.dylib       	       0x188029078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x188029078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x188029078 start_wqthread + 0

Thread 4:: com.apple.terminal.low-disk-space-handler
0   libsystem_kernel.dylib        	       0x187ff6c40 kevent + 8
1   Terminal                      	       0x104b880ac 0x104b84000 + 16556
2   Foundation                    	       0x188fcd71c __NSThread__start__ + 808
3   libsystem_pthread.dylib       	       0x18802e26c _pthread_start + 148
4   libsystem_pthread.dylib       	       0x18802908c thread_start + 8

Thread 5:: com.apple.terminal.sigchld-handler
0   libsystem_kernel.dylib        	       0x187ff1654 read + 8
1   Terminal                      	       0x104b92228 0x104b84000 + 57896
2   Foundation                    	       0x188fcd71c __NSThread__start__ + 808
3   libsystem_pthread.dylib       	       0x18802e26c _pthread_start + 148
4   libsystem_pthread.dylib       	       0x18802908c thread_start + 8

Thread 6:: com.apple.terminal.tty-io
0   libsystem_kernel.dylib        	       0x187ffb5b8 __select + 8
1   Terminal                      	       0x104b9361c 0x104b84000 + 63004
2   Foundation                    	       0x188fcd71c __NSThread__start__ + 808
3   libsystem_pthread.dylib       	       0x18802e26c _pthread_start + 148
4   libsystem_pthread.dylib       	       0x18802908c thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600002ecaec7   x1: 0x0000600000000015   x2: 0xfffffffffd135139   x3: 0x0000600000000020
    x4: 0x0000600002ecaec6   x5: 0x0000000000000006   x6: 0x0000000000000039   x7: 0x00000001882e77dc
    x8: 0xffffffffffffffff   x9: 0x0000000000000001  x10: 0x0000600002ecae80  x11: 0x000000000000003b
   x12: 0x000000000000003b  x13: 0x0000000000000007  x14: 0x0000000000000003  x15: 0x000060000380a250
   x16: 0x2f650001880450f0  x17: 0x0000000104c54680  x18: 0x0000000000000000  x19: 0x000000000000003c
   x20: 0x00006000004c4cf0  x21: 0x000000000000000b  x22: 0x000060000382e73b  x23: 0x000000016b279ed0
   x24: 0x00000001d4f1f6f9  x25: 0x000000000000000b  x26: 0x0000600002ec8fc0  x27: 0x0000000000000039
   x28: 0x0000000000000009   fp: 0x000000016b279e00   lr: 0x0000000104bac744
    sp: 0x000000016b279de0   pc: 0x0000000188045310 cpsr: 0xa0001000
   far: 0x00005ffffffffff5  esr: 0x92000005 (Data Abort) byte read Translation fault

Binary Images:
       0x188041000 -        0x188048fff libsystem_platform.dylib (*) <84fa5dd0-806c-310e-b047-479924cd688c> /usr/lib/system/libsystem_platform.dylib
       0x104b84000 -        0x104c53fff com.apple.Terminal (2.12.5) <5fa96871-c9f7-3d72-a2cb-677e75ee3db5> /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
       0x18ac16000 -        0x18bacdfff com.apple.AppKit (6.9) <153590c1-624c-38fb-8ffb-ba751bccbd16> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x188f71000 -        0x189361fff com.apple.Foundation (6.9) <886a3487-88a6-30bb-b179-1a92996c67cf> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x18e87a000 -        0x18e8eafff com.apple.AE (924) <0a3ab363-b23b-3956-8e4c-7c5f72680481> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
       0x190ce5000 -        0x191018fff com.apple.HIToolbox (2.1.1) <4a1d1f30-c79d-3502-b51f-9792adbd8e06> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x10506c000 -        0x1050cbfff dyld (*) <fbb89662-e6f2-3434-b542-f75185ac5e74> /usr/lib/dyld
       0x188027000 -        0x188033fff libsystem_pthread.dylib (*) <cee8bc77-6923-34d9-89a3-6f8f7279605e> /usr/lib/system/libsystem_pthread.dylib
       0x187fef000 -        0x188026fff libsystem_kernel.dylib (*) <1d7b3b8e-75a1-34ea-aa52-9f7c23155c55> /usr/lib/system/libsystem_kernel.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=794.5M resident=0K(0%) swapped_out_or_unallocated=794.5M(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        4 
Activity Tracing                   256K        1 
CG backing stores                  768K        4 
CG image                            96K        2 
ColorSync                          560K       25 
CoreGraphics                        16K        1 
CoreUI image data                   80K        1 
Foundation                        1504K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           251.4M       43 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        7 
Stack                             11.2M        7 
VM_ALLOCATE                        144K        9 
__AUTH                            1810K      152 
__AUTH_CONST                       9.9M      302 
__DATA                            8194K      288 
__DATA_CONST                      10.0M      303 
__DATA_DIRTY                       594K      101 
__FONT_DATA                          4K        1 
__LINKEDIT                       584.0M        4 
__OBJC_CONST                      1270K      127 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3152K        1 
__TEXT                           210.5M      319 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      233.6M       45 
shared memory                      880K       15 
===========                     =======  ======= 
TOTAL                              2.4G     1784 
TOTAL, minus reserved VM space     1.4G     1784 

-----------
Full Report
-----------

{"app_name":"Terminal","timestamp":"2022-05-17 13:38:46.00 +0800","app_version":"2.12.5","slice_uuid":"5fa96871-c9f7-3d72-a2cb-677e75ee3db5","build_version":"444","platform":1,"bundleID":"com.apple.Terminal","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"1DE7CD4A-8F1B-48B3-AE1D-EAE4BCE59394","name":"Terminal"}
{
  "uptime" : 590000,
  "procLaunch" : "2022-05-17 13:38:45.1318 +0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 14370559691107,
  "coalitionID" : 39044,
  "osVersion" : {
    "train" : "macOS 12.3.1",
    "build" : "21E258",
    "releaseType" : "User"
  },
  "captureTime" : "2022-05-17 13:38:45.4810 +0800",
  "incident" : "1DE7CD4A-8F1B-48B3-AE1D-EAE4BCE59394",
  "bug_type" : "309",
  "pid" : 80373,
  "procExitAbsTime" : 14370568042193,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Terminal",
  "procPath" : "\/System\/Applications\/Utilities\/Terminal.app\/Contents\/MacOS\/Terminal",
  "bundleInfo" : {"CFBundleShortVersionString":"2.12.5","CFBundleVersion":"444","CFBundleIdentifier":"com.apple.Terminal"},
  "buildInfo" : {"ProjectName":"Terminal","SourceVersion":"444000000000000","BuildVersion":"12"},
  "storeInfo" : {"deviceIdentifierForVendor":"461969E4-4B9D-57AE-B25B-E698E24C8B99","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "94BEED79-EFA8-7E1B-6C84-4BFAF24BFD18",
  "sip" : "enabled",
  "vmRegionInfo" : "0x5ffffffffff5 is not in any region.  Bytes after previous region: 105072079929334  Bytes before following region: 11\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00005ffffffffff5","rawCodes":[1,105553116266485],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00005ffffffffff5"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":80373},
  "vmregioninfo" : "0x5ffffffffff5 is not in any region.  Bytes after previous region: 105072079929334  Bytes before following region: 11\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9598726,"threadState":{"x":[{"value":105553165332167},{"value":105553116266517},{"value":18446744073660485945},{"value":105553116266528},{"value":105553165332166},{"value":6},{"value":57},{"value":6579714012,"symbolLocation":0,"symbol":"firstByteMark"},{"value":18446744073709551615},{"value":1},{"value":105553165332096},{"value":59},{"value":59},{"value":7},{"value":3},{"value":105553175028304},{"value":3415135899007340784,"symbolLocation":3415135892430389248,"symbol":"_platform_memmove"},{"value":4375004800},{"value":0},{"value":60},{"value":105553121266928},{"value":11},{"value":105553175177019},{"value":6092725968},{"value":7867594489,"objc-selector":"scrollRange"},{"value":11},{"value":105553165324224},{"value":57},{"value":9}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4374316868},"cpsr":{"value":2684358656},"fp":{"value":6092725760},"sp":{"value":6092725728},"esr":{"value":2449473541,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6576952080,"matchesCrashFrame":1},"far":{"value":105553116266485}},"queue":"com.apple.main-thread","frames":[{"imageOffset":17168,"symbol":"_platform_memmove","symbolLocation":544,"imageIndex":0},{"imageOffset":165700,"imageIndex":1},{"imageOffset":165432,"imageIndex":1},{"imageOffset":211356,"imageIndex":1},{"imageOffset":210984,"imageIndex":1},{"imageOffset":338564,"imageIndex":1},{"imageOffset":331676,"imageIndex":1},{"imageOffset":303632,"symbol":"-[NSApplication(NSPersistentUIRestorationSupport) restoreWindowWithIdentifier:state:completionHandler:]","symbolLocation":268,"imageIndex":2},{"imageOffset":302468,"symbol":"-[NSApplication(NSPersistentUIRestorationSupport) _restoreWindowWithRestoration:completionHandler:]","symbolLocation":572,"imageIndex":2},{"imageOffset":11982328,"symbol":"-[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:requireSecureCoding:completionHandler:]","symbolLocation":1456,"imageIndex":2},{"imageOffset":298936,"symbol":"-[NSPersistentUIManager restoreAllPersistentStateWithCompletionHandler:]","symbolLocation":332,"imageIndex":2},{"imageOffset":295624,"symbol":"-[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:completionHandler:]","symbolLocation":420,"imageIndex":2},{"imageOffset":3322592,"symbol":"-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]","symbolLocation":248,"imageIndex":2},{"imageOffset":293904,"symbol":"-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:]","symbolLocation":868,"imageIndex":2},{"imageOffset":223720,"symbol":"-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:]","symbolLocation":348,"imageIndex":3},{"imageOffset":223264,"symbol":"_NSAppleEventManagerGenericHandler","symbolLocation":96,"imageIndex":3},{"imageOffset":47348,"imageIndex":4},{"imageOffset":45644,"imageIndex":4},{"imageOffset":17400,"symbol":"aeProcessAppleEvent","symbolLocation":488,"imageIndex":4},{"imageOffset":283644,"symbol":"AEProcessAppleEvent","symbolLocation":68,"imageIndex":5},{"imageOffset":270084,"symbol":"_DPSNextEvent","symbolLocation":1844,"imageIndex":2},{"imageOffset":263204,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":2},{"imageOffset":206320,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":2},{"imageOffset":15624,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":2},{"imageOffset":20616,"symbol":"start","symbolLocation":516,"imageIndex":6}]},{"id":9598746,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":9598747,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":9598748,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":9598758,"name":"com.apple.terminal.low-disk-space-handler","frames":[{"imageOffset":31808,"symbol":"kevent","symbolLocation":8,"imageIndex":8},{"imageOffset":16556,"imageIndex":1},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":9598773,"name":"com.apple.terminal.sigchld-handler","frames":[{"imageOffset":9812,"symbol":"read","symbolLocation":8,"imageIndex":8},{"imageOffset":57896,"imageIndex":1},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":9598777,"name":"com.apple.terminal.tty-io","frames":[{"imageOffset":50616,"symbol":"__select","symbolLocation":8,"imageIndex":8},{"imageOffset":63004,"imageIndex":1},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6576934912,
    "size" : 32768,
    "uuid" : "84fa5dd0-806c-310e-b047-479924cd688c",
    "path" : "\/usr\/lib\/system\/libsystem_platform.dylib",
    "name" : "libsystem_platform.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4374151168,
    "CFBundleShortVersionString" : "2.12.5",
    "CFBundleIdentifier" : "com.apple.Terminal",
    "size" : 851968,
    "uuid" : "5fa96871-c9f7-3d72-a2cb-677e75ee3db5",
    "path" : "\/System\/Applications\/Utilities\/Terminal.app\/Contents\/MacOS\/Terminal",
    "name" : "Terminal",
    "CFBundleVersion" : "444"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6622896128,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "153590c1-624c-38fb-8ffb-ba751bccbd16",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.40.127"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6592860160,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4132864,
    "uuid" : "886a3487-88a6-30bb-b179-1a92996c67cf",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1858.112"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6686220288,
    "CFBundleShortVersionString" : "924",
    "CFBundleIdentifier" : "com.apple.AE",
    "size" : 462848,
    "uuid" : "0a3ab363-b23b-3956-8e4c-7c5f72680481",
    "path" : "\/System\/Library\/Frameworks\/CoreServices.framework\/Versions\/A\/Frameworks\/AE.framework\/Versions\/A\/AE",
    "name" : "AE",
    "CFBundleVersion" : "924"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6724407296,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "4a1d1f30-c79d-3502-b51f-9792adbd8e06",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4379295744,
    "size" : 393216,
    "uuid" : "fbb89662-e6f2-3434-b542-f75185ac5e74",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6576828416,
    "size" : 53248,
    "uuid" : "cee8bc77-6923-34d9-89a3-6f8f7279605e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6576599040,
    "size" : 229376,
    "uuid" : "1d7b3b8e-75a1-34ea-aa52-9f7c23155c55",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6573539328,
  "size" : 3136438272,
  "uuid" : "1df3dfc1-141a-35d0-a4e5-f1e113894c6e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=794.5M resident=0K(0%) swapped_out_or_unallocated=794.5M(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               512K        4 \nActivity Tracing                   256K        1 \nCG backing stores                  768K        4 \nCG image                            96K        2 \nColorSync                          560K       25 \nCoreGraphics                        16K        1 \nCoreUI image data                   80K        1 \nFoundation                        1504K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           251.4M       43 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        7 \nStack                             11.2M        7 \nVM_ALLOCATE                        144K        9 \n__AUTH                            1810K      152 \n__AUTH_CONST                       9.9M      302 \n__DATA                            8194K      288 \n__DATA_CONST                      10.0M      303 \n__DATA_DIRTY                       594K      101 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       584.0M        4 \n__OBJC_CONST                      1270K      127 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           210.5M      319 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      233.6M       45 \nshared memory                      880K       15 \n===========                     =======  ======= \nTOTAL                              2.4G     1784 \nTOTAL, minus reserved VM space     1.4G     1784 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "62702e3c52dd330db9df185d"
      },
      "deploymentId" : 240000121
    }
  ],
  "experiments" : [

  ]
}
}

Model: Macmini9,1, BootROM 7459.101.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: DELL P2717H, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Feb  8 2022 01:44:45 version 18.60.21.0.7.8.126 FWID 01-1cdae627
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB31Bus
USB Device: USB 2.0 BILLBOARD
USB Device: USB31Bus
USB Device: iQOO Neo5
USB Device: USB30Bus
USB Device: Razer DeathAdder 2013
USB Device: HID Keyboard
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by hyv1001** [comment]
是运行 bin/PilotEditor的时候闪退吗？
能否直接在Xcode中启动运行

**Comment by EmmaammE** [comment]
请问这个问题解决了吗
