### ISSUE TITLE
[悬赏] 编辑器模式下改变物体变换JoltPhysics 中的碰撞体无法跟随变换

### ISSUE THREAD

**Issue by Ol6rin** [BoomingTech/Piccolo#267]
[Bounty] Rigidbody in JoltPhysics not moving with objects transformed in Editor Mode

使用JoltPhysics碰撞体之后编辑器模式下拖动物体，在游戏模式中碰撞体没有更新。

简单尝试过直接设置碰撞体的position和rotation，但是碰撞体的质心会被更新到新的位置，丢失形状局部变换。

跪求熟悉JoltPhysics的大神帮助我们修复这个问题！修复后可以联系我们领取神秘奖励！

After we used rigidbody from JoltPhysics, if we transform objects in editor mode, rigidbodies are not updated.
We have tried simply set the position of rotation of the rigidbodies, but the center of mass will be updated to the new transform, local transform of shapes are lost.

If you're familiar with JoltPhysics, could you please help us fix this bug? If the bug is fixed, please contact us for a present.

**Comment by Hubch** [comment]
是不是没有手动唤醒呢？
