### ISSUE TITLE
为什么不能 Debug 

### ISSUE THREAD

**Issue by franklzt** [BoomingTech/Piccolo#297]
想要Debug,但这一句报错 m_vulkan_api_version = VK_API_VERSION_1_0;  
Windows 10 
N 卡 960

**Comment by ShenMian** [comment]
请参考 #23.

**Comment by Ol6rin** [comment]
> 想要Debug,但这一句报错 m_vulkan_api_version = VK_API_VERSION_1_0; Windows 10 N 卡 960

之前有人遇到过这个问题，可以先试一下 #23 中的解决方案
