### ISSUE TITLE
Win10，VS2019下成功编译但运行失败

### ISSUE THREAD

**Issue by LoveDLWujing** [BoomingTech/Piccolo#308]
**Actual behavior | 实际行为**
能够编译成功（Release，Debug x64）
但点击exe时无反应，debug运行时报错

**Screenshots/Logs | 截图/日志**
![1](https://user-images.githubusercontent.com/32677829/180231842-3483a3f0-171b-48bc-91d7-ab77572a1f43.PNG)
![2](https://user-images.githubusercontent.com/32677829/180231767-0f3a7186-4917-468f-9a71-bd5bc73ae7a1.PNG)

**Desktop | 桌面环境**
 - OS:  Windows
 - Version：Windows 10 专业版
 - CPU Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
 - GPU NVIDIA GeForce GTX 1050 Ti
 - Memory 12GB
 - Compiler MSVC2019

**Additional context | 补充信息**

**Comment by 751500365** [comment]
遇到同样问题，而且 down 下来的zip 总是解压出错，不知哪里出问题了。

**Comment by ccqil** [comment]
这是你CPU不支持AVX2指令集。
要运行的话请修改以下文件
https://github.com/BoomingTech/Piccolo/blob/214542257eeda28b09495fe38910d42fa2ba48b4/engine/3rdparty/JoltPhysics/Build/CMakeLists.txt#L14-L21
把你CPU不支持的指令集改成OFF就行了。

**Comment by LoveDLWujing** [comment]
> 这是你CPU不支持AVX2指令集。 要运行的话请修改以下文件
> 
> https://github.com/BoomingTech/Piccolo/blob/214542257eeda28b09495fe38910d42fa2ba48b4/engine/3rdparty/JoltPhysics/Build/CMakeLists.txt#L14-L21
> 
> 把你CPU不支持的指令集改成OFF就行了。

非常感谢！！
