### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by jiantaozhang** [BoomingTech/Piccolo#318]
build后跑不起来 
从vs直接debug，报错如下
```
// GetTrianglesContext.h  91行
// 0xC000001D: Illegal Instruction
int num_verts = 4 * (1 << inDetailLevel);
```

两台电脑
- CPU为i7 10700     （可以正常运行）
- CPU为E3V2  （不能正常运行）   指令集相比上面的i7   少了 AVX2 FMA3
不确定和这个有没有关系
求大佬解惑~

**Comment by ccqil** [comment]
对，是因为你的CPU不支持AVX2指令集。
如果你要运行的话，你要把JoltPhysics的CMake文件里的相关选项设置一下。
https://github.com/BoomingTech/Piccolo/blob/214542257eeda28b09495fe38910d42fa2ba48b4/engine/3rdparty/JoltPhysics/Build/CMakeLists.txt#L14-L21
就把这里你CPU不支持的指令集改成OFF就行了。
