### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by ShenMian** [BoomingTech/Piccolo#319]
[Piccolo引擎运行时架构](https://github.com/BoomingTech/Piccolo/wiki/Piccolo%E5%BC%95%E6%93%8E%E8%BF%90%E8%A1%8C%E6%97%B6%E6%9E%B6%E6%9E%84)中的 core.public_singleton 貌似已经在 https://github.com/BoomingTech/Piccolo/pull/200 中被移除了.

**Comment by Ol6rin** [comment]
PublicSingleton确实已经移除了，文档这里更新漏了，会尽快更新一下
