### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ginn-gu** [BoomingTech/Piccolo#329]
**Describe the bug | Bug描述**
Piccolo 使用的BRDB LUT资产文件brdf_schilk.hdr是OpenGL的坐标格式吧（原点在左下）
fragment shader "mesh_lighting.inl"中：
highp vec2 brdfLUT = texture(brdfLUT_sampler, vec2(clamp(dot(N, V), 0.0, 1.0), roughness)).rg;
是否应为：
highp vec2 brdfLUT = texture(brdfLUT_sampler, vec2(clamp(dot(N, V), 0.0, 1.0), 1 - roughness)).rg;

**Comment by YuqiaoZhang** [comment]
HI Ginn,
Thanks for following Piccolo.   
Actually, according to the convention, the texture will be filpped during the loading process, and thus we don't need to flip the UV in the shader.  
For example, here is the [GLSL](https://github.com/selfshadow/ltc_code/blob/master/webgl/shaders/ltc/ltc_quad.fs#L433) and [HLSL](https://github.com/EpicGames/UnrealEngine/blob/4.27/Engine/Shaders/Private/RectLight.ush#L449) code of the same logic in LTC.  
And here are some other facts which may help you comprehend this LUT case. Evidently, the artists are createing the model in 3dsMax which is based on Direct3D. However, when we render the model by Vulkan, we don't need to flip the UV of the model. This is analogous to this case when we are sampling the LUT.

**Comment by ginn-gu** [comment]
Thanks

**Comment by YuqiaoZhang** [comment]
Hi Ginn,
I have verified this problem again and I realize that there do exist some bugs in the loading process.  
Actually, the UV coords of Vulkan is the same as Direct3D. And we do NOT need to flip the texture during the loading process.  
However, this texture is flipped during the loading process.  
Perhaps this is a big bug, and we need to change the loading process and the related code.
