### ISSUE TITLE
run fails on ubuntu22.04

### ISSUE THREAD

**Issue by hastaluegoph** [BoomingTech/Piccolo#340]
**Describe the bug | Bug描述**
加载资源文件是路径貌似多了一层

**Steps to reproduce | 如何复现**
1. 编译按照readme ./build_linux.sh debug make
2. 运行build/engine/source/editor/Piccolo

**Expected behavior | 预期行为**
    
**Actual behavior | 实际行为**
A clear and concise description of what actually happened.

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.
![图片](https://user-images.githubusercontent.com/33288604/189016100-fda8f8a3-7f51-4dd4-98fa-03bc1b03e079.png)

**Desktop | 桌面环境**
 - OS: linux
 - Version ubuntu22.04
 - CPU Intel Core i7-12700H
 - GPU NVidia RTX 3070
 - Memory 16G
 - Compiler g++ 11.2

**Additional context | 补充信息**

**Comment by Ol6rin** [comment]
感谢反馈！因为Ubuntu下面没有IDE，所以Ubuntu下推荐的运行方式是通过bin目录下的可执行文件，那里的配置文件是可以保证能够正确读到资产的。编译目录下的配置文件只能保证WIndows下VisualStudio开发环境使用。
