### ISSUE TITLE
PiccoloParser 使用vs调试，跳过断点直接运行完成

### ISSUE THREAD

**Issue by NINTING** [BoomingTech/Piccolo#348]
**Describe the bug | Bug描述**
PiccoloParser 使用vs调试，跳过断点直接运行完成

**Steps to reproduce | 如何复现**
直接在VS中对PiccoloParser 进行断点调试

**Expected behavior | 预期行为**
   可以进入断点

**Actual behavior | 实际行为**
A clear and concise description of what actually happened.
直接运行完成，无法进入断点

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/31238314/189586005-fe4dc6b2-13df-405f-a1fa-7b185b8203dc.png)

![image](https://user-images.githubusercontent.com/31238314/189586060-a8b3f738-0327-4248-8e80-0d045c6d21c1.png)

**Desktop | 桌面环境**

windows 
vs2019

**Additional context | 补充信息**

**Comment by Ol6rin** [comment]
Debug版PiccoloParser没有配置生成调试信息，可以试着先在工程配置中打开。
