### ISSUE TITLE
Bug Report Win10锁屏后引擎会弹出错误窗口，并崩溃

### ISSUE THREAD

**Issue by PeterJohn** [BoomingTech/Piccolo#350]
**Describe the bug | Bug描述**
Win10锁屏后引擎会弹出错误窗口，并崩溃

**Steps to reproduce | 如何复现**
1. 运行引擎
2. Win10锁屏（win+L）
3. 解锁回到Win10桌面

**Expected behavior | 预期行为**
引擎正常运行
    
**Actual behavior | 实际行为**
A clear and concise description of what actually happened.
引擎停止运行，并弹出一个Microsoft Visual C++ Runtime Library错误窗口，CMD窗口中也提示一个Assertion failed

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/7891680/189684568-ea3283ad-20b1-45d3-857a-43420274dc6f.png)

**Desktop | 桌面环境**
 - OS: [e.g. Windows, macOS, Linux] Windows
 - Version [e.g. Win10, Bug Sur, Ubuntu20] Win 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ] Intel i7-8565U
 - GPU [AMD 6800 XT, NVidia RTX 3090] Intel UHD Graphics 620
 - Memory [e.g. 16GB] 8GB
 - Compiler [e.g. MSVC2019, Clang13, G++7.0] MSVC 2022

**Additional context | 补充信息**

**Comment by hyv1001** [comment]
@kwbm plz check this issue

**Comment by kwbm** [comment]
本地单卡环境未能复现，可能是多显卡引起的问题，可以尝试在资源管理器中禁用一款再测试
