### ISSUE TITLE
Bug Report: Ubuntu20.04 执行无build-tools

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [BoomingTech/Piccolo#361]
**Describe the bug | Bug描述**
Ubuntu20.04 执行无build-tools

**Steps to reproduce | 如何复现**
1.  安装ubuntu20.04
2.  执行命令
3.  sudo [执行脚本]
4.  
5. 

**Expected behavior | 预期行为**
开始编译
    
**Actual behavior | 实际行为**
A clear and concise description of what actually happened.
无build-tools

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.

**Desktop | 桌面环境**
 - OS: [e.g.  Linux]
 - Version [e.g.  Ubuntu20]
-  虚拟机
 - Memory [e.g. 16GB]
 - Compiler [e.g. MSVC2019, Clang13, G++7.0]

**Additional context | 补充信息**

**Comment by hyv1001** [comment]
请描述的更详细一些，build-tools指的是什么？
Ubuntu下应该是直接运行 [build_linux.sh](https://github.com/BoomingTech/Piccolo/blob/main/build_linux.sh)

**Comment by liangzai12** [comment]
请根据readme说明安装ubuntu所需的工具与库
