### ISSUE TITLE
Ubuntu-22.04-64bit运行出现错误

### ISSUE THREAD

**Issue by RussellZhou-hub** [BoomingTech/Piccolo#368]
**Describe the bug | Bug描述**
使用clion打开后build成功，运行后，load asset 错误

**Screenshots/Logs | 截图/日志**
![image](https://user-images.githubusercontent.com/61743623/194854632-01e345f2-8780-47c4-b01a-a7a4fa372c1b.png)

**Desktop | 桌面环境**
 - OS: ubuntu22.04
 - CPU  Intel I9-9900k 
 - GPU rtx 2060
 - Memory 16GB
 - Compiler CMake, Clang13, G++7.0

**Comment by Ol6rin** [comment]
Ubuntu下由于没有统一的IDE，通过bash从bin目录下直接运行PiccoloEditor是可以的，针对不同的IDE可以自行配置路径
