### ISSUE TITLE
build failed windows

### ISSUE THREAD

**Issue by escplean** [BoomingTech/Piccolo#402]
PS E:\CG\games104\Piccolo> cmake . -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2022/12/9 23:19:06。
    节点 1 上的项目“E:\CG\games104\Piccolo\build\CMakeFiles\3.23.1\VCTargetsPath.vcxproj”(默认目标)。     
    PrepareForBuild:
      正在创建目录“x64\Debug\”。
      正在创建目录“x64\Debug\VCTargetsPath.tlog\”。
    InitializeBuildStatus:
      正在创建“x64\Debug\VCTargetsPath.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
    FinalizeBuildStatus:
      正在删除文件“x64\Debug\VCTargetsPath.tlog\unsuccessfulbuild”。
      正在对“x64\Debug\VCTargetsPath.tlog\VCTargetsPath.lastbuildstate”执行 Touch 任务。
    已完成生成项目“E:\CG\games104\Piccolo\build\CMakeFiles\3.23.1\VCTargetsPath.vcxproj”(默认目标)的操作。

    已成功生成。
        0 个错误

    已用时间 00:00:00.30

-- Configuring incomplete, errors occurred!
See also "E:/CG/games104/Piccolo/build/CMakeFiles/CMakeOutput.log".

**Comment by Nikolameow** [comment]
我也遇到了这个问题，请问是怎么解决的
