### ISSUE TITLE
Debug Error!

### ISSUE THREAD

**Issue by Alex-gift-hit** [BoomingTech/Piccolo#418]
**Describe the bug | Bug描述**
软件版本 Piccolo main

使用build_windows.bat可以正常的打开编辑器。

不过打开.sln文件后:进行debug
Set PiccoliEditor project as Start Project
Build solution
Run piccoloEditor start debugging。

会出现报错

[Assertion failed: instance != VK_NULL_HANDLE, file F:\Piccolo-main\engine\3rdparty\glfw\src\vulkan.c, line 305
error] [Piccolo::VulkanRHI::createInstance] vk create instance
[error] [Piccolo::VulkanRHI::initializeDebugMessenger] failed to set up debug messenger!

![5{VUJW89_VKYZ%OUZ` FRVV](https://user-images.githubusercontent.com/74054788/210565863-8c503c8d-de9e-4352-b85e-fceb96cb47d0.png)

**Desktop | 桌面环境**
 - OS: Windows
 - Version:Win10
 - GPU :AMD Radeon 535DX
 - Memory :4 GB
 - Compiler : VS 2019
 - Vulkan Sdk: 1.3.236.0

**Additional context | 补充信息**
![)Q(KSI95_(W6~ISAJKJTDO0](https://user-images.githubusercontent.com/74054788/210565874-05549db5-a5e2-4a65-93d0-a4e63e05b3bf.png)

感谢您的回复(●'◡'●)

**Comment by ShenMian** [comment]
问题可能出在:  

https://github.com/BoomingTech/Piccolo/blob/65379de9f67fe9c1d809e925c459d397e680ea8a/engine/source/runtime/function/render/interface/vulkan/vulkan_rhi.cpp#L666

可以尝试查看一下这个函数的返回值, 然后对照[手册](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateInstance.html)看看具体的错误原因.  

不太明白 `VulkanRHI::createInstance` 报错的时候怎么出现了其他地方的断言失败提示, 而且位置还在 `VulkanRHI::createInstance` 的后面.

**Comment by Alex-gift-hit** [comment]
感谢大家的帮助，半个多月，尝试了很多办法。小引擎版本都换了几个，vulkan SDK 也换了几遍还是没有解决。

今天下决心一定要解决这个问题。把过去的issues几乎看了个遍。发现好多问题都和驱动有关，就试着更新一下驱动。问题就解决了😌

这电脑还是hp2016年出的老电脑了。

AMD Radeon GPU驱动太老套了17.1(17年的)，现在换到22.6.1就可以用了。

具体方法：
如何查找 AMD 显卡产品的最新兼容驱动程序：https://www.amd.com/zh-hans/support/kb/faq/gpu-56

但是里面没有这个电脑相关的驱动，又找到了这个。
“如果您使用 AMD 产品选择器无法找到 AMD 显卡产品，则说明您的显卡产品可能经过定制并预装在 OEM 台式或笔记本个人电脑中，因此驱动程序只能从 OEM 合作伙伴处获得。有关 AMD OEM 合作伙伴的更多信息，请参阅知识库文章：: [AMD 合作伙伴: 板卡厂商、原始设备制造商和系统集成商的配置。(https://www.amd.com/zh-hans/support/kb/faq/gpu-91)”

于是去了hp的官网，根据自己的电脑，下载到了对应的显卡驱动，安装了新的驱动。一切问题就解决了，可以正常的调试了。

再次感谢课程组。同时希望我的解决办法可以帮到其他的小伙伴。

**Comment by wkcn** [comment]
Arch Linux intel集成显卡可以安装：
```bash
sudo pacman -S vulkan-intel
```
