### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by LoogLong** [BoomingTech/Piccolo#458]
**Describe the bug | Bug描述**
内存分配不足的bug

**Steps to reproduce | 如何复现**
![image](https://github.com/BoomingTech/Piccolo/assets/86428208/05d6d0ec-372c-446d-8b63-1788c7428391)

**Expected behavior | 预期行为**
    
**Actual behavior | 实际行为**
A clear and concise description of what actually happened.

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.

**Desktop | 桌面环境**
 - OS: [e.g. Windows, macOS, Linux]
 - Version [e.g. Win10, Bug Sur, Ubuntu20]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]
 - Compiler [e.g. MSVC2019, Clang13, G++7.0]

**Additional context | 补充信息**

**Comment by LoogLong** [comment]
创建scale axis的函数EditorScaleAxis::EditorScaleAxis预分配的内存不足后续逻辑使用导致的崩溃。

**Comment by hyv1001** [comment]
@kwbm plz check this issue

**Comment by F-Mu** [comment]
赞，终于编译通过了

**Comment by kwbm** [comment]
谢谢反馈，应该是这个提交有些问题，https://github.com/BoomingTech/Piccolo/commit/89f1dddc105c0cbe7c33313a4cfe809d36f08947
为避免影响其他同学体验，已经先回退，原问题得在原反馈人电脑上再分析一下
