### ISSUE TITLE
Bug Report 启动崩溃，分配内存越界

### ISSUE THREAD

**Issue by jun-nda** [BoomingTech/Piccolo#460]
有好几个地方可能会崩溃，每次启动都不一样，都是崩在了分配内存上，大部分情况下是倒在了 vulkan CommandBuffer这里。
环境：Win11，VS2022
![image](https://github.com/BoomingTech/Piccolo/assets/105705552/375caa49-8959-4275-98b8-0cbdda66dcc4)

![image](https://github.com/BoomingTech/Piccolo/assets/105705552/a2119014-a20c-40c5-b336-e0b8bc128012)
![image](https://github.com/BoomingTech/Piccolo/assets/105705552/e64411d2-43de-4549-941e-1888e1bff910)
出现次数最多的三个地方。
机器内存剩余充足
![image](https://github.com/BoomingTech/Piccolo/assets/105705552/7bcf594e-a54d-4226-80a5-46d5cfb0e2e2)

**Comment by LoogLong** [comment]
和我遇到的一样。是访问越界导致的。稍微修改一下就行了

**Comment by LoogLong** [comment]
https://github.com/BoomingTech/Piccolo/issues/458

**Comment by hyv1001** [comment]
@kwbm plz check this issue

**Comment by kwbm** [comment]
谢谢反馈，应该是这个提交有些问题，https://github.com/BoomingTech/Piccolo/commit/89f1dddc105c0cbe7c33313a4cfe809d36f08947
为避免影响其他同学体验，已经先回退，原问题得在原反馈人电脑上再分析一下
