### ISSUE TITLE
如何使用renderdoc抓帧

### ISSUE THREAD

**Issue by boooooommmmmm** [BoomingTech/Piccolo#469]
你好，
我在使用renderdoc启动编译好的PiccoloEditor.exe时，会提示`vk create device`。请问需要怎么配置renderdoc

![temp](https://github.com/BoomingTech/Piccolo/assets/25132777/90cd941b-cf29-4d10-9120-c9c3205680e3)

**Comment by kwbm** [comment]
尝试升级驱动或者相关软件版本试试呢？
我本地测试环境下不需要特别配置renderdoc可以抓帧：
- renderdoc 1.18
- vulkan sdk 1.298.1
- Window 10 22H2
- Nvidia驱动545.92

**Comment by wavMe** [comment]
遇到了同样的问题，请问如何解决的呢？

**Comment by wavMe** [comment]
https://games-cn.org/forums/topic/guanyuvulkanshiyongrenderdocdecuowu/
后来的朋友请参考这个帖子 卸载wegame即可
